### ISSUE TITLE
IFOF ROI order

### ISSUE THREAD

**Issue by steso** [jyeatman/AFQ#7]
Is there any reason for switching the order of the right IFOF ROIs?
In AFQ_SegmentFiberGroups, for the right IFOF, roi2 is used as roi1 and vice versa:
`'IFO_roi1_L.nii.gz', 'IFO_roi2_L.nii.gz'; 'IFO_roi2_R.nii.gz', 'IFO_roi1_R.nii.gz'; ...`

**Comment by jyeatman** [comment]
Fixed
